CREATE SCHEMA IF NOT EXISTS bonvino;
SET SCHEMA bonvino;

CREATE TABLE IF NOT EXISTS bonvino.bodegas
(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    COORDENADAS_UBICACION VARCHAR(30) NOT NULL,
    FECHA_ULTIMA_ACTUALIZACION TIMESTAMP,
    HISTORIA VARCHAR(350),
    PERIODO_ACTUALIZACION INT,
    PRIMARY KEY (ID),
);

CREATE TABLE IF NOT EXISTS bonvino.enofilos
(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    IMAGEN VARCHAR(100) NOT NULL,
    COORDENADAS_UBICACION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
);

CREATE TABLE IF NOT EXISTS bonvino.repository
(
    ID              INT AUTO_INCREMENT NOT NULL,
    OWNER_ID        INT,
    REPOSITORY_NAME VARCHAR(255)       NOT NULL,
    DESCRIPTION     VARCHAR(500),
    LAST_UPDATE     TIMESTAMP,
    URL             VARCHAR(255)       NOT NULL,
    STARS           REAL,
    PRIMARY KEY (ID),
    FOREIGN KEY (OWNER_ID) REFERENCES bonvino.users (ID)
);

CREATE TABLE IF NOT EXISTS bonvino.language
(
    ID   INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255)       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS bonvino.language_repository
(
    ID_LANGUAGE   INT,
    ID_REPOSITORY INT,
    PRIMARY KEY (ID_LANGUAGE, ID_REPOSITORY),
    FOREIGN KEY (ID_LANGUAGE) REFERENCES bonvino.language (ID),
    FOREIGN KEY (ID_REPOSITORY) REFERENCES bonvino.repository (ID)
);

CREATE TABLE IF NOT EXISTS bonvino.tag
(
    ID            INT AUTO_INCREMENT NOT NULL,
    NAME          VARCHAR(255)       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS bonvino.tag_repository
(
    ID_TAG        INT,
    ID_REPOSITORY INT,
    PRIMARY KEY (ID_TAG, ID_REPOSITORY),
    FOREIGN KEY (ID_TAG) REFERENCES bonvino.tag (ID),
    FOREIGN KEY (ID_REPOSITORY) REFERENCES bonvino.repository (ID)
);
